In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [12]:
import warnings
warnings.filterwarnings("ignore")

TASK-10A: Please model the AD dataset using the SVM, Decision Tree, and Random Forest algorithms.

Please apply train test split (%75-%25) Then grid search (hyperparameter tuning) Then classification report and confusion matrix (on the test dataset) Then compare the findings from the three algorithms

In [2]:
data = pd.read_excel("Temporary_data3_Left_Right_Copy.xlsx")
data.head()

SEX  EDUC  MARISTAT  INDEPEND  RESIDENC  NACCFAM  ANYMEDS  SMOKYRS  \
0    2    18         1         1         1        1        1        0   
1    1    11         1         1         1        1        1        0   
2    2    16         1         1         1        1        1       10   
3    1    14         1         1         1        0        1        0   
4    1    16         1         1         2        0        1       50   

   NACCTBI  DIABETES  ...   RSUPFR  RSUPFRM  RSUPPAR  RSUPPARM  RSUPTEM  \
0        0         0  ...  27.9038   2.2157  10.3481    1.7014  13.4250   
1        0         0  ...  29.0600   2.6900   9.2500    1.6300  14.8800   
2        0         1  ...  33.0000   2.5400  13.6900    1.5600  16.2300   
3        0         1  ...  31.6800   2.4100   9.6400    1.4500  15.1100   
4        0         0  ...  28.0631   1.9501   9.1125    1.0427  13.3763   

   RSUPTEMM  RSUPMAR  RSUPMARM  RTRTEM  RTRTEMM  
0    1.7419   9.8700    1.6792  0.8906   1.1947  
1    2.3000   7.2700    1.8900  1.3800   2.0300  
2    2.0700  10.1100    1.8400  1.0100   1.5000  
3    1.6400  10.3900    1.8300  0.7400   1.1000  
4    1.6270   7.5844    1.4595  0.6638   0.8527  

[5 rows x 186 columns]

In [3]:
Y = data["CDRGLOB"]
data.drop(columns = ["CDRGLOB"], axis = 1, inplace = True)

In [4]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(data, Y,train_size=0.75,stratify=Y)

In [11]:
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier() 
dtc_params = { 'criterion':['gini', 'entropy'],
               'min_samples_split':[2,3,4],
               'min_samples_leaf':[1,2,3],
               'max_features':['sqrt', 'log2']}
dtc_grid = GridSearchCV(dtc, dtc_params, cv=5)
dtc_grid.fit(Xtrain, Ytrain)
dtc_grid.best_params_
grid_pred = dtc_grid.predict(Xtest)

print("Classification Report for Decision Tree Classifier:\n",classification_report(Ytest, grid_pred))
print("Confusion Matrix for Decision Tree Classifier:\n",confusion_matrix(Ytest, grid_pred))

Classification Report for Decision Tree Classifier:
               precision    recall  f1-score   support

           0       0.71      0.70      0.70       162
           1       0.42      0.45      0.43       124
           2       0.29      0.24      0.26        41
           3       0.18      0.17      0.17        12

    accuracy                           0.53       339
   macro avg       0.40      0.39      0.39       339
weighted avg       0.53      0.53      0.53       339

Confusion Matrix for Decision Tree Classifier:
 [[113  47   2   0]
 [ 45  56  17   6]
 [  1  27  10   3]
 [  0   4   6   2]]


In [16]:
from sklearn.svm import SVC

svc=SVC()
svc_params= {'max_iter': [10,100,1000],
             'class_weight' : ['balanced'],
             'C': [0.1, 1, 100],
             'gamma': [1, 0.1, 0.01, 0.0001],
             }
svc_grid = GridSearchCV(svc, svc_params, refit=True)
svc_grid.fit(Xtrain, Ytrain)
svc_grid.best_params_
grid_pred = svc_grid.predict(Xtest) 

print("Classification Report for Support Vector Classification:\n",classification_report(Ytest, grid_pred))
print("Confusion Matrix for Support Vector Classification:\n",confusion_matrix(Ytest, grid_pred))

Classification Report for Support Vector Classification:
               precision    recall  f1-score   support

           0       0.64      0.62      0.63       162
           1       0.47      0.55      0.51       124
           2       0.30      0.22      0.25        41
           3       0.25      0.17      0.20        12

    accuracy                           0.53       339
   macro avg       0.41      0.39      0.40       339
weighted avg       0.52      0.53      0.52       339

Confusion Matrix for Support Vector Classification:
 [[100  58   4   0]
 [ 41  68  14   1]
 [ 12  15   9   5]
 [  3   4   3   2]]


In [19]:
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()
rfc_params = {  'n_estimators': [10, 25, 50, 100],
                'criterion': ['gini', 'entropy'],
                'max_depth': [1, 2, 3, 4, 5,7,10],
                'min_samples_split': [2, 3, 4],
              }
rfc_grid = GridSearchCV(rfc, rfc_params, refit=True)
rfc_grid.fit(Xtrain, Ytrain)
rfc_grid.best_params_
grid_pred = rfc_grid.predict(Xtest) 

print("Classification Report for Random Forest Classifier:\n",classification_report(Ytest, grid_pred))
print("Confusion Matrix for Random Forest Classifier:\n",confusion_matrix(Ytest, grid_pred))

Classification Report for Random Forest Classifier:
               precision    recall  f1-score   support

           0       0.78      0.90      0.84       162
           1       0.62      0.68      0.65       124
           2       0.61      0.27      0.37        41
           3       1.00      0.08      0.15        12

    accuracy                           0.71       339
   macro avg       0.75      0.48      0.50       339
weighted avg       0.71      0.71      0.69       339

Confusion Matrix for Random Forest Classifier:
 [[145  17   0   0]
 [ 39  84   1   0]
 [  1  29  11   0]
 [  0   5   6   1]]
